apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-pqxt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-pqxt
    app.kubernetes.io/part-of: test-app-rill
  name: devfile-sample-python-basic-pqxt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-pqxt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-pqxt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-urqy-tenant/test-app-rill/devfile-sample-python-basic-pqxt@sha256:a3b653e346080f654b2f13615f3cc07fa62cc48829eaa44e2d5aeddceae694ef
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
